### ISSUE TITLE
Electric Spirit Catcher Disapears after inserting net

### ISSUE THREAD

**Issue by Bunnky** [JustAHuman-xD/SpiritsUnchained#15]
## Description (Required)

After placing an electric spirit catcher and putting an empty net inside, the catcher disappears with an error log (below)
## Steps to reproduce the Issue (Required)

Place Spirit Catcher, put net inside and wait about 3-5 seconds. Machine disappears.
## Expected behavior (Required)

The machine to work, or do something.
## Server Log / Error Report

https://pastebin.com/ipxpmQvu   (Nether placed)
https://pastebin.com/qaxi8fep   (Overworld placed)
## Environment (Required)

![image](https://user-images.githubusercontent.com/6545569/202954024-6b789bb2-a916-48a6-af5a-fed2cfadf5db.png)

**Comment by JustAHuman-xD** [comment]
Oh that's strange, I'll take a look real fast (sorry I didn't get to this sooner been busy with holidays)

**Comment by JustAHuman-xD** [comment]
Should be fixed with that latest commit! Sorry about the inconvenience!

**Comment by JustAHuman-xD** [comment]
I can't test this right now but if this works feel free to close the issue or leave a note that it did!

**Comment by Bunnky** [comment]
Working perfectly :) Thank you @JustAHuman-xD

**Comment by JustAHuman-xD** [comment]
Great!
