### ISSUE TITLE
Language file load for fresh install

### ISSUE THREAD

**Issue by ybw0014** [JustAHuman-xD/SpiritsUnchained#18]
## Description (Required)

When loading the language file for fresh install, the language file isn't read, causing everything "Invalid Path!".

```
👻  Invalid Path!
This addon adds a new mechanic to your Slimefun experience, Invalid Path!! Invalid Path! can be found roaming freely the wild or can sometimes release when killing a mob. Players can catch/bottle Invalid Path! to discover each types unique effect on its user. But be careful, Invalid Path! may not always be Invalid Path!! 
```

## Steps to reproduce the Issue (Required)

Fresh install.

## Expected behavior (Required)

Language file is loaded correctly on fresh install.

## Environment (Required)

 - Minecraft Version: paper 1.19.2
 - CS-CoreLib Version:
 - Slimefun Version: 1035
 - Plugin Version: 16

**Comment by JustAHuman-xD** [comment]
Oh how fun

**Comment by JustAHuman-xD** [comment]
Interestingly enough this only applies for when the file is generated, if the server restarts it loads itself correctly from that point. I am looking to figure out why rn, but until then it's not too terrible.

**Comment by JustAHuman-xD** [comment]
Fixed it, will be in the next build
