### ISSUE TITLE
Color codes are not translated in placeholder

### ISSUE THREAD

**Issue by ybw0014** [JustAHuman-xD/SpiritsUnchained#19]
## Description (Required)

Some messages that have placeholders are not colored after replacing the placeholder.
For example, in `language.yml`, `messages.traits.used_passive` has `{tier_color_and_mob_type}` placeholder, which will display the mob type and color. However, the color symbol is not translated.
There may be more messages having this small bug. Above is the only one I found during my test of translation.

## Expected behavior (Required)

Color codes in placeholder are translated.

## Environment (Required)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version:
 - Slimefun Version: 1035
 - Plugin Version: 16

**Comment by JustAHuman-xD** [comment]
What do you mean by the color symbol is not translated? I guess I am a bit confused

**Comment by ybw0014** [comment]
`&` is used as a common alternative color code. plugin would read a string and call `ChatColor.translateAlternateColorCode` method (`ChatColors.color` is the equivalent in Slimefun) to translate this symbol to `§`, the one Minecraft recognizes.
I see your translation system would parse this color code, but the replaced placeholder still contains `&` and this wont be translated.

**Comment by JustAHuman-xD** [comment]
Will be fixed in the next build, the source of the problem was actually that it was replacing it with the traits name instead of the mob type.
