### ISSUE TITLE
2 Suggestions; Storage, Portable Passing On

### ISSUE THREAD

**Issue by Bunnky** [JustAHuman-xD/SpiritsUnchained#23]
**Suggestion: Spirit Storage**
Spirits take up a ton of inventory room on their own. I'm not sure if it's possible, but having some sort of storage device that would contain spirits only would be incredible. Maybe only passives? I'm thinking of having many passives with me all the time if I can, and with other content my inventory is already small. I can understand if this isn't workable. I would also support a block storage of some kind, for only spirits. I currently use backpacks to store, and with networks this may not even be needed :)

This was also suggested: 
![image](https://user-images.githubusercontent.com/6545569/207867945-4babea06-8617-435f-b133-8f8342a4c294.png)

**Suggestion: Portable Passing On**
If players sit at spawners with "spirit catching" builds that trap them in a 1 block area, it becomes an issue of them stacking up (dealing with caps I'm not sure how hostiles work, but i'm assuming they add to the cap). But I may not want to catch any of them, maybe I just want them to go away so I don't affect the spirit cap. I was thinking some kind of tool that would let the spirit pass on (not giving any benefit, just basically removing it), and could require ectoplasm? Something like that. Maybe a Spirit remover tool like this could be harder to make, since it gives a really good benefit? Maybe it could even take SF power?

Thanks for reading, fantastic work!

**Comment by JustAHuman-xD** [comment]
Sounds interesting. Just finished finals week so I'll take some time looking into this. I've had similar suggestions for the passing on and have an idea in mind.

**Comment by JustAHuman-xD** [comment]
Based off of this and also other suggestions, what do you think about natural spirit passing on. Basically after a spirit is spawned it has a set amount of time until it passes on. If no one catches it before that time it just passes on and is removed from the cap. I’m thinking making this number dependant on tier, lower the tier, lower the time until it passes on. I don't want to limit this to any item because it effects all of the players and server performance depending on the configuration.

**Comment by Bunnky** [comment]
Yea I think this is a fine solution :) To be fair, I wasn't sure if this already happened with natural spawned, but for the mob-spawned hostiles it didn't seem like it. I like the idea of tier based timings as well, I think that's pretty fair (and not needing a tool helps with more inventory management so thats a +1 from me :P )

**Comment by JustAHuman-xD** [comment]
Awesome! I'll start work on this after school and can probably get an update out within a few days. As for the other 2 suggestions I'm  hesitant on implementing a bag even just for the passives. As the main trade off of using the spirits is the inventory slots they take. For the transmitter idea I've had similar thoughts but haven't reached a consensus, trying to find a way to balance it, like make it use energy etc.

**Comment by JustAHuman-xD** [comment]
For the natural spirit passing on it's in the latest push to the dev fork. Once it's tested because there are other changes It'll be released in the next update!
