### ISSUE TITLE
Better Brewer error

### ISSUE THREAD

**Issue by xMikux** [JustAHuman-xD/SpiritsUnchained#29]
## Description (Required)
When using Witch Spirit (Better Brewer) will cause error.

## Steps to reproduce the Issue (Required)
1. Get Witch Spirit and some Glass Bottle
2. Right-click and see the error

![image](https://github.com/JustAHuman-xD/SpiritsUnchained/assets/26039249/fee0d07b-d616-4b46-8388-8711aaad9bc1)
(Also the error mob type placeholder is not showing)

## Expected behavior (Required)
Should not cause the error.

## Server Log / Error Report
https://pastebin.com/GBZrmr7M

## Environment (Required)
![image](https://github.com/JustAHuman-xD/SpiritsUnchained/assets/26039249/6aff0523-2341-4176-b541-13e3c4603b95)

**Comment by dentatar** [comment]
+1 same issue here
Server: Paper 1.20.4 build 462
SF: Dev build 1143
Addon: Dev build 24

**Comment by JustAHuman-xD** [comment]
I swear I fixed this whoops, I'll look into it today

**Comment by dentatar** [comment]
Hello. I'm sorry to bother, but this is till broken…

**Comment by JustAHuman-xD** [comment]
> Hello. I'm sorry to bother, but this is till broken…

Can you give me the logs on Dev 24? It should be fixed on that version

**Comment by dentatar** [comment]
Oh sorry i was using slightly outdated versions on my testing network… It's actually working in my main environment, you can close the issue
