### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by cherylgames** [JustAHuman-xD/SpiritsUnchained#34]
I can't get it to load properly on the server I am making what version do I need for the latest slimefun

**Comment by JustAHuman-xD** [comment]
Sorry for the delay for some reason GitHub didn't give me any notification for this! Can you give logs, server info, etc. Spirits requires Paper 1.19.x+

**Comment by cherylgames** [comment]
Hey nvm sorry for taking ur time

**Comment by JustAHuman-xD** [comment]
> Hey nvm sorry for taking ur time

Oh no problem! Glad you got it figured out
